owner: ArturiaPendragon
repo: uptime-status

sites:
  - name: Datacenter - Helsinki (FI)
    url: $IP_HELSINKI
    icon: https://findicons.com/files/icons/2118/nuvola/128/server.png
    check: "tcp-ping"
    port: 42874
    assignees:
    - ArturiaPendragon
  - name: Flood Service - Helsinki (FI)
    url: http://$IP_HELSINKI:47192/login
    icon: https://raw.githubusercontent.com/jesec/flood/master/flood.svg
    assignees:
    - ArturiaPendragon
  - name: Datacenter - Paris (FR)
    url: $IP_PARIS
    icon: https://findicons.com/files/icons/2118/nuvola/128/server.png
    check: "tcp-ping"
    maxResponseTime: 10000
    assignees:
    - ArturiaPendragon
  - name: Ishtar Project - Paris (FR)
    url: $IP_PARIS
    icon: https://docs.nest.land/img/logo.svg
    check: "tcp-ping"
    maxResponseTime: 10000
    assignees:
    - ArturiaPendragon
  - name: API - Spain (ES)
    url: $URL_API
    icon: https://docs.nest.land/img/logo.svg
    maxResponseTime: 4000
    expectedStatusCodes:
      - 200
      - 500
    assignees:
    - ArturiaPendragon
  - name: Arturia Pendragon Website
    url: https://www.ovh.com/fr/
    icon: https://docs.nest.land/img/logo.svg
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
      - 500
    assignees:
    - ArturiaPendragon
    
notifications:
  - type: discord
 
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: status.mioscape.my.id
  baseUrl: /uptime-status
  favicon: $PERSONAL_ICON
  logoUrl: $PERSONAL_ICON
  themeUrl: https://nest-status-src.vercel.app/assets/theme.css
  name: Arturia Pendragon - État des serveurs
  #introTitle: "Welcome to our **mioscape.my.id** server status page."
  #introMessage: You can get updates on how our systems are doing. If there are interruptions to service, we will post a note here.
  navbar:
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
