owner: ArturiaPendragon
repo: uptime-status

sites:
  - name: Arturia Pendragon Website
    url: $PERSONAL_WEBSITE
    icon: https://findicons.com/files/icons/2118/nuvola/128/server.png
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
      - 500
    assignees:
    - ArturiaPendragon
  - name: API
    url: $URL_API
    icon: https://findicons.com/files/icons/2118/nuvola/128/server.png
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
      - 500
    assignees:
    - ArturiaPendragon
  - name: Datacenter (Paris) - OVH
    url: $IP_PARIS
    icon: https://findicons.com/files/icons/2118/nuvola/128/server.png
    check: "tcp-ping"
    port: 80
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
      - 500
    assignees:
    - ArturiaPendragon
  - name: Datacenter (Helsinki) - Hetzner
    url: $IP_HELSINKI
    icon: https://findicons.com/files/icons/2118/nuvola/128/server.png
    check: "tcp-ping"
    port: 80
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
      - 500
    assignees:
    - ArturiaPendragon
  - name: Ishtar Project
    url: $IP_PARIS
    icon: https://findicons.com/files/icons/2118/nuvola/128/server.png
    check: "tcp-ping"
    port: 80
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
      - 500
    assignees:
    - ArturiaPendragon
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: status.mioscape.my.id
  baseUrl: /uptime-status
  favicon: $PERSONAL_ICON
  logoUrl: $PERSONAL_ICON
  name: Arturia Pendragon - État des serveurs
  #introTitle: "Welcome to our **mioscape.my.id** server status page."
  #introMessage: You can get updates on how our systems are doing. If there are interruptions to service, we will post a note here.
  theme: ocean
  navbar:
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
